linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gocritic
    - goimports
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - revive
    - govet
    - funlen
    #- gosec
    #- unused

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec