flows:
  login:
    modules:
      - id: "login"
        type: "login"
        properties:
  registration:
    modules:
      - id: "registration"
        type: "registration"
        properties:
          primaryField:
            dataStore: "email"
            name: "email"
            prompt: "Email"
          additionalFields:
            - dataStore: "name"
              prompt: "Name"
              name: "name"

userDataStore:
  type: "mongodb"
  properties:
    url:  "mongodb://root:changeme@localhost:27017"
    database:   "users"
    collection: "users"
    userAttributes:
      - "name"
      - "email"

session:
  type: "stateful" #could be also stateful
  expires: 60000
  dataStore:
    type: "mongo"
    properties:
      url: "mongodb://root:changeme@localhost:27017"
      database:   "session"
      collection: "sessions"

server:
  cors:
    allowedOrigins:
      - http://localhost:3000


