name: Build

on:
  push:
  pull_request:
    branches: [master]

jobs:
  # golangci:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:          
  #         version: latest

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build project
      run: make default

